import axios from 'axios';

export async function POST(req) {
    const formData = await req.json();
    console.log('Received request:', formData);

    try {
        const aiResponse = await axios.post(
            `${process.env.SERVICE_AI_URL}export-video/`,
            formData, {
            headers: { 'Content-Type': 'application/json' }
        }

        );
        console.log('AI service response:', aiResponse.data);

        if (!aiResponse.data || !aiResponse.data.data) {
            return new Response(JSON.stringify({ error: 'No script generated by AI service' }), {
                status: 500,
                headers: { 'Content-Type': 'application/json' },
            });
        }
        console.log('AI service response data:', aiResponse.data.data);
        const videoUrl = 'https://example.com/video.mp4'; // Replace with actual URL from AI service response

        return new Response(JSON.stringify({ videoUrl }), {
            status: 200,
            headers: { 'Content-Type': 'application/json' },
        });

    } catch (error) {
        console.error('Error call AI service:', error.response?.data || error.message);

        return new Response(JSON.stringify({ error: 'Error call AI service' }), {
            status: 500,
            headers: { 'Content-Type': 'application/json' },
        });
    }
}
