import { Noto_Sans } from "next/font/google";
import { Noto_Sans_JP, Noto_Sans_KR, Noto_Sans_SC, Noto_Sans_Thai } from 'next/font/google'
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "./provider";
import { Toaster } from "@/components/ui/sonner"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const notoSans = Noto_Sans({
  subsets: ["latin", "vietnamese"],
  weight: ["400", "500", "700"],
  display: "swap",
});

const notoJP = Noto_Sans_JP({
  weight: ['400'],
  subsets: ['latin'], // optional but safe
  display: 'swap',
})

const notoKR = Noto_Sans_KR({
  weight: ['400'],
  subsets: ['latin'], // optional
  display: 'swap',
})

const notoSC = Noto_Sans_SC({
  weight: ['400'],
  subsets: ['latin'], // optional
  display: 'swap',
})

const notoThai = Noto_Sans_Thai({
  weight: ['400'],
  subsets: ['thai'], // ✅ bắt buộc để preload không lỗi
  display: 'swap',
})



export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${notoSans.className} ${notoJP.className} ${notoKR.className} ${notoSC.className} ${notoThai.className}`}>
        <body >
          <Provider>
            {children}
          </Provider>
          <Toaster />
        </body>
      </html>

    </ClerkProvider>

  );
}
