import axios from 'axios';

export async function POST(req) {
    const formData = await req.json();

    try {
        const aiResponse = await axios.post(
            `${process.env.SERVICE_AI_URL}generate-raw-script`,
            formData, {
            headers: { 'Content-Type': 'application/json' }
        }

        );

        if (!aiResponse.data || !aiResponse.data.script) {
            return new Response(JSON.stringify({ error: 'No script generated by AI service' }), {
                status: 500,
                headers: { 'Content-Type': 'application/json' },
            });
        }

        return new Response(JSON.stringify({ script: aiResponse.data.script, title: aiResponse.data.title }), {
            status: 200,
            headers: { 'Content-Type': 'application/json' },
        });

    } catch (error) {
        console.error('Lỗi gọi AI service:', error.response?.data || error.message);

        return new Response(JSON.stringify({ error: 'Lỗi khi gọi AI service' }), {
            status: 500,
            headers: { 'Content-Type': 'application/json' },
        });
    }
}
