import axios from 'axios';

export async function POST(req) {
    const formData = await req.json();
    console.log('Received request:', formData);

    try {
        const aiResponse = await axios.post(
            `${process.env.SERVICE_AI_URL}script/full-script`,
            formData, {
            headers: { 'Content-Type': 'application/json' }
        }

        );

        if (!aiResponse.data || !aiResponse.data.full_script) {
            return new Response(JSON.stringify({ error: 'No script generated by AI service' }), {
                status: 500,
                headers: { 'Content-Type': 'application/json' },
            });
        }

        return new Response(JSON.stringify(aiResponse.data), {
            status: 200,
            headers: { 'Content-Type': 'application/json' },
        });

    } catch (error) {
        console.error('Error call AI service:', error.response?.data || error.message);

        return new Response(JSON.stringify({ error: 'Error call AI service' }), {
            status: 500,
            headers: { 'Content-Type': 'application/json' },
        });
    }
}
